[package]
name        = "kprint-formatting"
version     = "0.1.0"
authors     = { workspace = true }
edition     = { workspace = true }
description = "The dprint formatting engine and intermediate representation."
repository  = { workspace = true }
license     = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[dependencies]
bumpalo       = { workspace = true, features = ["allocator-api2", "collections"] }
hashbrown     = { workspace = true }
rustc-hash    = { workspace = true }
serde         = { workspace = true }
unicode-width = { workspace = true }

[features]
default = []
tracing = []
