# yaml-language-server: $schema=https://raw.githubusercontent.com/kjanat/actionlint/e6a3f3cb997b50f1598b778785a0f3e31801e55b/actionlint.schema.json
---
policy:
  cache-call-unrestricted: true
  cache-operation: true
  cache-write-untrusted: true
  disallow-suppressions: true
  require-commit-hash: true
  require-job-timeout: true
  require-permissions: true
