[package]
name                 = "dprint-core-macros"
version              = "0.1.0"
authors              = ["David Sherret <dsherret@gmail.com>"]
edition.workspace    = true
description          = "Core formatting macros for dprint-core."
homepage             = "https://github.com/kjanat/dprint/tree/HEAD/crates/core-macros"
repository.workspace = true
license              = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn   = { version = "1.0", features = ["full"] }
