[package]
name = "dprint-config-schema"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false
repository = "https://github.com/dprint/dprint"
description = "The JSON schema of dprint's configuration file, with the plugins' schemas composed in."

[dependencies]
anyhow = { workspace = true }
percent-encoding = "=2.3.1"
schemars = { version = "=1.2.2", features = ["preserve_order"] }
serde = { workspace = true }
serde_json = { workspace = true }
url = "=2.5.4"

[dev-dependencies]
boon = "0.6.1"
pretty_assertions = "1.4.0"
