[package]
name                 = "dprint-discovery"
version              = "0.1.0"
edition.workspace    = true
repository.workspace = true
license.workspace    = true

[dependencies]
dprint-host-api = { workspace = true }
dprint-platform = { workspace = true }

tree-fucker = { workspace = true }

anyhow      = { workspace = true }
parking_lot = { workspace = true }
tokio       = { workspace = true, features = ["io-std"] }

[dev-dependencies]
dprint-test-support         = { workspace = true }
path-clean.workspace        = true
pretty_assertions.workspace = true
sys_traits                  = { workspace = true, features = ["memory"] }
tempfile.workspace          = true
