[package]
name        = "kprint-development"
version     = "0.11.0"
authors     = { workspace = true }
edition     = { workspace = true }
description = "Helper functions for testing dprint plugins."
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
console          = { workspace = true }
file_test_runner = { workspace = true }
serde_json       = { workspace = true }
similar          = { workspace = true }
