# :schema https://www.schemastore.org/cargo-config.json

[alias]
build-dprint = "build -p dprint --release --bin dprint"
lint         = "clippy --workspace --all-features --all-targets"
run-dprint   = "run -qp dprint --bin dprint --"

[build]
rustflags = "-Dwarnings"

[target]
# statically link the c runtime https://github.com/rust-lang/rust/issues/100874
'cfg(all(windows, target_env = "msvc"))'.rustflags = ["-C", "target-feature=+crt-static"]
