# :schema https://www.schemastore.org/cargo-config.json

[alias]
lint = "clippy --workspace --all-features --all-targets"

# [build]
# rustflags = "-Dwarnings"

[env]
RUSTFLAGS = "-Dwarnings"

[target]
# statically link the c runtime https://github.com/rust-lang/rust/issues/100874
'cfg(all(windows, target_env = "msvc"))'.rustflags = ["-C", "target-feature=+crt-static"]
