use anyhow::Result;
use anyhow::bail;
use serde_json::Map;
use serde_json::Value;

/// The schema of dprint's configuration file (also served at
/// https://dprint.dev/schemas/v0.json).
const DPRINT_CONFIG_SCHEMA: &str = include_str!("../commands/lsp/config_schema.json");

/// The name of the schema file `dprint schema` creates for a configuration
/// file. When there's one next to a configuration file, the commands that
/// change its plugins keep it up to date.
pub const CONFIG_SCHEMA_FILE_NAME: &str = "dprint.schema.json";

/// The schema of a plugin's configuration.
pub struct PluginSchema {
  pub config_key: String,
  pub schema: Value,
}

/// Builds one self-contained schema for a configuration file: dprint's schema,
/// with each plugin's schema for its table.
///
/// The plugin schemas are copied in rather than referred to with `allOf`,
/// because some tools check each part of an `allOf` separately when they
/// report properties a schema doesn't have (ex. tombi's strict mode), which
/// would flag a plugin's `associations` and dprint's own properties.
pub fn build_config_schema(plugins: Vec<PluginSchema>) -> Result<Value> {
  let Value::Object(mut root) = serde_json::from_str::<Value>(DPRINT_CONFIG_SCHEMA)? else {
    bail!("Expected dprint's configuration schema to be an object.");
  };
  // the references stay within this file
  root.shift_remove("$id");
  // what every plugin table may have (ex. `associations`), which a plugin's
  // own schema doesn't describe
  let plugin_table_properties = root
    .get("additionalProperties")
    .and_then(|value| value.get("properties"))
    .and_then(|value| value.as_object())
    .cloned()
    .unwrap_or_default();

  for plugin in plugins {
    let Value::Object(mut schema) = plugin.schema else {
      continue;
    };
    schema.shift_remove("$schema");
    schema.shift_remove("$id");
    let definition_name = format!("plugin:{}", plugin.config_key);
    let pointer = format!("#/definitions/{}", escape_pointer_segment(&definition_name));
    // the plugin's references to itself now point to where it's copied to
    let mut schema = {
      let mut value = Value::Object(schema);
      rewrite_local_refs(&mut value, &pointer);
      match value {
        Value::Object(schema) => schema,
        _ => unreachable!(),
      }
    };
    let properties = schema.entry("properties").or_insert_with(|| Value::Object(Map::new())).as_object_mut();
    if let Some(properties) = properties {
      for (key, value) in &plugin_table_properties {
        properties.entry(key.clone()).or_insert_with(|| value.clone());
      }
    }
    object_entry(&mut root, "definitions").insert(definition_name, Value::Object(schema));
    object_entry(&mut root, "properties").insert(plugin.config_key, serde_json::json!({ "$ref": pointer }));
  }

  let mut result = Map::new();
  // put the comment near the top
  if let Some(schema) = root.shift_remove("$schema") {
    result.insert("$schema".to_string(), schema);
  }
  result.insert(
    "$comment".to_string(),
    Value::String(format!(
      "Generated by `dprint schema` for the configuration's plugins. `dprint add` and `dprint config update` regenerate a {} next to the configuration file.",
      CONFIG_SCHEMA_FILE_NAME
    )),
  );
  result.extend(root);
  Ok(Value::Object(result))
}

fn object_entry<'a>(object: &'a mut Map<String, Value>, key: &str) -> &'a mut Map<String, Value> {
  let value = object.entry(key.to_string()).or_insert_with(|| Value::Object(Map::new()));
  if !value.is_object() {
    *value = Value::Object(Map::new());
  }
  value.as_object_mut().unwrap()
}

/// Prefixes the references within the schema to itself (`#...`) with where
/// the schema is moved to.
fn rewrite_local_refs(value: &mut Value, pointer: &str) {
  match value {
    Value::Object(object) => {
      for (key, value) in object.iter_mut() {
        if key == "$ref"
          && let Value::String(reference) = value
          && let Some(rest) = reference.strip_prefix('#')
        {
          *reference = format!("{}{}", pointer, rest);
        } else {
          rewrite_local_refs(value, pointer);
        }
      }
    }
    Value::Array(values) => {
      for value in values {
        rewrite_local_refs(value, pointer);
      }
    }
    _ => {}
  }
}

/// Escapes a JSON pointer segment (RFC 6901).
fn escape_pointer_segment(segment: &str) -> String {
  segment.replace('~', "~0").replace('/', "~1")
}

#[cfg(test)]
mod test {
  use pretty_assertions::assert_eq;
  use serde_json::json;

  use super::*;

  #[test]
  fn copies_plugin_schemas_into_the_configuration_schema() {
    let schema = build_config_schema(vec![PluginSchema {
      config_key: "typescript".to_string(),
      schema: json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://plugins.dprint.dev/typescript/schema.json",
        "type": "object",
        "definitions": { "quoteStyle": { "type": "string", "enum": ["alwaysSingle", "preferSingle"] } },
        "properties": {
          "quoteStyle": { "$ref": "#/definitions/quoteStyle" },
          "external": { "$ref": "https://example.com/schema.json#/definitions/x" },
        },
      }),
    }])
    .unwrap();

    let root = schema.as_object().unwrap();
    assert_eq!(root.keys().take(2).collect::<Vec<_>>(), vec!["$schema", "$comment"]);
    assert!(root.get("$id").is_none());
    // dprint's own properties are there
    assert!(schema["properties"]["lineWidth"].is_object());
    assert!(schema["properties"]["plugins"].is_object());
    assert_eq!(schema["properties"]["typescript"], json!({ "$ref": "#/definitions/plugin:typescript" }));

    let plugin = &schema["definitions"]["plugin:typescript"];
    assert!(plugin.get("$id").is_none() && plugin.get("$schema").is_none());
    // its references to itself point to where it was copied to, others stay
    assert_eq!(
      plugin["properties"]["quoteStyle"],
      json!({ "$ref": "#/definitions/plugin:typescript/definitions/quoteStyle" })
    );
    assert_eq!(
      plugin["properties"]["external"],
      json!({ "$ref": "https://example.com/schema.json#/definitions/x" })
    );
    // dprint's properties of every plugin table were added
    for key in ["associations", "locked", "overrides"] {
      assert_eq!(plugin["properties"][key], schema["additionalProperties"]["properties"][key], "{}", key);
    }
    // dprint's own definitions are still there for those
    assert!(schema["definitions"]["pluginConfigOverride"].is_object());
  }

  #[test]
  fn escapes_plugin_config_keys_in_pointers() {
    let schema = build_config_schema(vec![PluginSchema {
      config_key: "a/b~c".to_string(),
      schema: json!({ "properties": { "x": { "$ref": "#" } } }),
    }])
    .unwrap();
    assert_eq!(schema["properties"]["a/b~c"], json!({ "$ref": "#/definitions/plugin:a~1b~0c" }));
    assert_eq!(
      schema["definitions"]["plugin:a/b~c"]["properties"]["x"],
      json!({ "$ref": "#/definitions/plugin:a~1b~0c" })
    );
  }
}
