[package]
name        = "dprint-core"
version     = "0.70.0"
authors     = ["Kaj Kowalski <info@kajkowalski.nl>", "David Sherret <dsherret@gmail.com>"]
edition     = { workspace = true }
description = "Core library for dprint."
homepage    = "https://github.com/kjanat/dprint/tree/HEAD/crates/dprint-core"
repository  = { workspace = true }
license     = { workspace = true }
keywords    = ["formatter", "formatting"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
dprint-async-runtime  = { workspace = true, optional = true }
dprint-communication  = { workspace = true, optional = true }
dprint-configuration  = { workspace = true }
dprint-formatting     = { workspace = true, optional = true }
dprint-owned-child    = { workspace = true, optional = true }
dprint-plugin-types   = { workspace = true, optional = true }
dprint-process-plugin = { workspace = true, optional = true }
dprint-wasm-plugin    = { workspace = true, optional = true }

[dev-dependencies]
dprint-core-macros = { path = "../dprint-core-macros", version = "0.1.0" }

[features]
default       = ["formatting"]
async_runtime = ["dep:dprint-async-runtime", "dprint-plugin-types?/async_runtime"]
communication = ["async_runtime", "dep:dprint-communication"]
formatting    = ["dep:dprint-formatting"]
process       = ["communication", "dep:dprint-owned-child", "dep:dprint-plugin-types", "dep:dprint-process-plugin"]
tracing       = ["dprint-formatting/tracing", "formatting"]
wasm          = ["dep:dprint-plugin-types", "dep:dprint-wasm-plugin"]
