[package]
name       = "test-process-plugin"
version    = "0.1.0"
authors    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }

[dependencies]
dprint-core = { workspace = true, default-features = true, features = ["process"] }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
