[package]
name       = "test-process-plugin"
version    = "0.1.0"
authors    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }

[dependencies]
kprint-async-runtime  = { workspace = true }
kprint-configuration  = { workspace = true }
kprint-plugin-types   = { workspace = true }
kprint-process-plugin = { workspace = true }
serde                 = { workspace = true }
tokio                 = { workspace = true }
