[package]
name       = "test-process-plugin"
version    = "0.1.0"
authors    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }

[dependencies]
dprint-async-runtime  = { workspace = true }
dprint-configuration  = { workspace = true }
dprint-plugin-types   = { workspace = true }
dprint-process-plugin = { workspace = true }
serde                 = { workspace = true }
tokio                 = { workspace = true }
