[package]
name        = "kprint-process-plugin"
version     = "0.1.0"
authors     = { workspace = true }
edition     = { workspace = true }
description = "The dprint process plugin API and stdio protocol."
repository  = { workspace = true }
license     = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[dependencies]
kprint-async-runtime = { workspace = true }
kprint-communication = { workspace = true }
kprint-configuration = { workspace = true }
kprint-owned-child   = { workspace = true }
kprint-plugin-types  = { workspace = true, features = ["async_runtime"] }
serde                = { workspace = true }
serde_json           = { workspace = true }
thiserror            = { workspace = true }
tokio                = { workspace = true }
tokio-util           = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }

[target."cfg(windows)".dependencies]
winapi = { workspace = true, features = [
  "handleapi",
  "jobapi",
  "jobapi2",
  "processthreadsapi",
  "synchapi",
  "tlhelp32",
  "winbase",
  "winerror",
  "winnt"
] }
