[package]
name        = "dprint-core"
version     = "0.70.0"
authors     = ["Kaj Kowalski <info@kajkowalski.nl>", "David Sherret <dsherret@gmail.com>"]
edition     = { workspace = true }
description = "Core library for dprint."
homepage    = "https://github.com/kjanat/dprint/tree/HEAD/crates/core"
repository  = { workspace = true }
license     = { workspace = true }
keywords    = ["formatter", "formatting"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
async-trait       = { workspace = true, optional = true }
bumpalo           = { workspace = true, features = ["allocator-api2", "collections"], optional = true }
crossbeam-channel = { workspace = true, optional = true }
futures           = { workspace = true, optional = true }
hashbrown         = { workspace = true, optional = true }
indexmap          = { workspace = true }
parking_lot       = { workspace = true, optional = true }
rustc-hash        = { workspace = true, optional = true }
serde             = { workspace = true }
serde_json        = { workspace = true, optional = true }
thiserror         = { workspace = true, optional = true }
tokio             = { workspace = true, optional = true }
tokio-util        = { workspace = true, optional = true }
unicode-width     = { workspace = true, optional = true }

[target.'cfg(not(any(target_os = "unknown", target_arch = "wasm32")))'.dependencies]
libc = { workspace = true, optional = true }

[target."cfg(windows)".dependencies.winapi]
workspace = true
features  = ["handleapi", "jobapi", "jobapi2", "processthreadsapi", "synchapi", "tlhelp32", "winbase", "winerror", "winnt"]
optional  = true

[features]
default = ["formatting"]

async_runtime = ["async-trait", "futures", "parking_lot", "tokio", "tokio-util"]
communication = ["async_runtime", "crossbeam-channel"]
formatting    = ["bumpalo", "hashbrown", "rustc-hash", "unicode-width"]
process       = ["communication", "libc", "serde_json", "thiserror", "winapi"]
tracing       = ["formatting"]
wasm          = ["serde_json", "thiserror"]
