name: Website
on:
  workflow_dispatch:
    inputs: { deploy: { description: Deploy to GitHub Pages, type: boolean, default: false } }
  push: &m { branches: [main, master] }
  pull_request: *m
permissions: {}

jobs:
  build:
    runs-on: &slim ubuntu-slim
    timeout-minutes: 5
    cancel-timeout-minutes: 1
    permissions: { contents: &r read }
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - parallel:
          - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
          - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
          - uses: kjanat/runner@ad30f34c7352d89884b6d03febd9b16b4807ed56 # v0.27.1
      - name: Do it all
        working-directory: website
        run: runner install -s playground:build playground:test build:ci
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with: { path: "website/_site" }

  deploy:
    needs: build
    runs-on: *slim
    timeout-minutes: 2
    cancel-timeout-minutes: 1
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.repository_owner == 'kjanat'
    permissions: { contents: *r, pages: &w write, id-token: *w }
    environment: { name: github-pages, url: "${{ steps.deployment.outputs.page_url }}" }
    concurrency: { group: "pages-deploy", cancel-in-progress: false }
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
